### Requisação para a raiz da apliação
GET http://localhost:5085

### Listar produtos
GET http://localhost:5085/api/produto/listar

### Cadastrar produto
POST http://localhost:5085/api/produto/cadastrar/mouse